export const zhCN = {
  nav: {
    defaultBadge: "页面抓取",
    imageConverter: "图片转换",
    logAnalyzer: "日志分析",
    options: [
      { name: "浅层抓取", route: "/" },
      { name: "深度抓取", route: "/global" },
      { name: "日志分析", route: "/serverlogs" },
      { name: "PPC 模拟器", route: "/ppc" },
    ],
    resetSuccess: "已完全重置，RustySEO 将在 3 秒后重新加载",
    resetError: "重置 RustySEO 失败，请重试。",
    cacheCleared: "已清除 RustySEO 缓存",
  },
  settings: {
    tabs: {
      crawler: "爬虫",
      network: "网络",
      links: "链接",
      extraction: "数据",
      logs: "日志",
      integrations: "集成",
    },
    title: "设置",
    saving: "保存中",
    subtitle: "配置爬虫行为与性能参数",
    loading: "正在加载设置…",
    loadFailed: "设置加载失败",
    retry: "重试",
    unknownError: "未知错误",
    sections: {
      general: "常规",
      timing: "时序与限速",
      requestNetwork: "请求与网络",
      rendering: "JavaScript 与渲染",
      linkProcessor: "链接处理",
      contentExtraction: "内容提取",
      databaseBatching: "数据库与批处理",
      logProcessing: "日志处理",
      fileUpload: "文件上传",
      pageSpeedInsights: "PageSpeed Insights",
      gsc: "Google Search Console",
    },
  },
  integrations: {
    gscModal: {
      searchTypes: {
        domain: "网域属性",
        site: "网址属性",
      },
      durations: {
        oneMonth: "1 个月",
        threeMonths: "3 个月",
        sixMonths: "6 个月",
        twelveMonths: "12 个月",
        sixteenMonths: "16 个月",
      },
      rows: {
        max: "最大值",
      },
      errors: {
        clientId: "Client ID 为必填项",
        projectId: "Project ID 为必填项",
        clientSecret: "Client Secret 为必填项",
        url: "URL 为必填项",
        propertyType: "属性类型为必选项",
        range: "日期范围为必选项",
        rows: "行数为必选项",
      },
      saved: "凭据已保存",
      saveFailed: "保存凭据失败",
      title: "输入凭据",
      instructions: "查看说明",
      projectId: "项目 ID",
      clientId: "客户端 ID",
      clientSecret: "客户端密钥",
      url: "网址",
      propertyType: "属性类型",
      propertyTypePlaceholder: "选择属性类型",
      dateRange: "日期范围",
      dateRangePlaceholder: "选择时间范围",
      rowsLabel: "行数",
      rowsPlaceholder: "选择行数",
      confirm: "确认",
      placeholders: {
        projectId: "输入项目 ID",
        clientId: "输入客户端 ID",
        clientSecret: "输入客户端密钥",
        url: "输入网址",
      },
    },
    gscWizard: {
      missingCredentials: "请输入 Client ID 和 Client Secret",
      exchangeFailed: "用授权码换取令牌失败",
      openingGoogle: "正在浏览器中打开 Google 登录…",
      authStartFailed: "启动授权流程失败",
      noProperties: "未找到 Search Console 属性",
      fetchPropertiesFailed: "获取属性列表失败",
      selectProperty: "请选择一个属性",
      connected: "Search Console 连接成功！",
      saveFailed: "保存连接设置失败",
      title: "连接 Search Console",
      stepOf: "第 {step} 步，共 4 步",
      step1: {
        title: "解锁更深层的搜索洞察",
        description:
          "连接 Google Search Console，在 RustySEO 中直接查看实时排名、展现和点击数据。",
        globalReach: "全局视角",
        globalReachDesc: "跟踪站点整体搜索表现",
        secureAccess: "安全接入",
        secureAccessDesc: "使用 Google 官方 API 授权",
        start: "开始配置",
      },
      step2: {
        title: "API 配置",
        description: "输入你的 Google Cloud Project 信息。",
        guide: "查看指南",
        back: "上一步",
        continue: "继续",
        placeholders: {
          clientId: "xxx-xxx.apps.googleusercontent.com",
          projectId: "my-awesome-project",
          clientSecret: "GOCSPX-xxxxxxxxxxxxxxxx",
        },
      },
      step3: {
        title: "授权访问",
        description:
          "接下来会打开安全的 Google 登录窗口，用于授权 RustySEO 读取你的 Search Console 数据。",
        connect: "使用 Google 连接",
        readonly:
          "RustySEO 仅请求对你的 Search Console 数据的只读权限。",
        popupBlocked:
          "如果弹窗未出现，请检查浏览器或系统是否拦截了弹窗。",
      },
      step4: {
        title: "选择属性",
        description: "选择你希望在当前工作区中跟踪的网站属性。",
        complete: "完成设置",
      },
    },
    ga4Wizard: {
      missingCredentials: "请输入 Client ID 和 Client Secret",
      exchangeFailed: "用授权码换取令牌失败",
      openingGoogle: "正在浏览器中打开 Google 登录…",
      authStartFailed: "启动授权流程失败",
      noProperties: "未找到 GA4 属性",
      fetchPropertiesFailed: "获取属性列表失败",
      selectProperty: "请选择一个属性",
      connected: "Google Analytics 已连接成功！请刷新表格。",
      saveFailed: "保存连接设置失败",
      title: "连接 GA4",
      stepOf: "第 {step} 步，共 4 步",
      step1: {
        title: "分析用户行为",
        description:
          "连接 Google Analytics 4，跟踪会话、跳出率和用户参与度。",
        userInsights: "用户洞察",
        userInsightsDesc: "更了解你的受众",
        secureAuth: "安全授权",
        secureAuthDesc: "使用 Google 官方 OAuth 连接",
        start: "开始配置",
      },
      step2: {
        title: "API 配置",
        description: "输入 GA4 所需的 Google Cloud Project 信息。",
        back: "上一步",
        continue: "继续",
        placeholders: {
          clientId: "xxx-xxx.apps.googleusercontent.com",
          projectId: "my-awesome-project",
          clientSecret: "GOCSPX-xxxxxxxxxxxxxxxx",
        },
      },
      step3: {
        title: "授权 GA4 访问",
        description: "接下来会打开安全的 Google 登录窗口。",
        connect: "使用 Google 连接",
        popupBlocked: "如果弹窗失败，请检查是否拦截了弹窗。",
      },
      step4: {
        title: "选择 GA4 属性",
        description: "选择你希望跟踪的 GA4 属性。",
        propertyId: "ID",
        complete: "完成设置",
      },
    },
    gemini: {
      loading: "正在加载配置…",
      title: "Google Gemini",
      subtitle: "配置 Google AI Studio 集成",
      apiKey: "API 密钥",
      getKey: "获取密钥",
      hideKey: "隐藏密钥",
      showKey: "显示密钥",
      chooseModel: "选择模型",
      refreshModels: "刷新模型",
      selectModel: "选择模型",
      usingDefaultModels:
        "当前使用默认模型列表。输入 API 密钥并点击“刷新模型”可获取全部可用模型。",
      secureNotice:
        "你的 API 密钥仅安全存储在本机，不会上传到我们的服务器。请求时只会直接发送给 Google API。",
      test: "测试连接",
      save: "保存并启用",
      fetchModelsFailed: "获取模型列表失败",
      fetchModelsFallback: "将使用默认模型列表，请检查 API 密钥。",
      enterApiKey: "请输入 API 密钥",
      saveSuccess: "Gemini 设置已保存",
      saveSuccessDesc: "Google Gemini 已设为当前 AI 提供方。",
      saveFailed: "保存设置失败",
      testNeedKey: "请先输入 API 密钥再测试",
      testSuccess: "连接成功",
      testSuccessDesc: "{model} 响应正常。",
      testFailed: "连接失败",
      noResponse: "模型没有返回结果",
      noConfig: "未找到现有 Gemini 配置。",
    },
    ollama: {
      title: "如需使用本地模型，请先安装 Ollama。",
      steps: [
        "访问 Ollama 官网：ollama.com。",
        "选择适合你的 AI 模型。",
        "按照说明完成下载与安装。",
        "安装完成后，在下方选择模型。",
        "重启应用。",
      ],
      modelLabel: "Ollama AI 模型",
      modelPlaceholder: "选择模型",
      selectedSuccess: "模型选择成功",
      saveFailed: "保存模型失败",
      connect: "连接模型",
    },
    powerBi: {
      required: "请输入 Power BI 链接",
      saved: "Power BI 链接已保存，正在重新加载 RustySEO…",
      saveFailed: "保存链接失败",
      title: "Power BI 报表链接",
      placeholder: "https://app.powerbi.com/reportEmbed?reportId=...",
      helper: "输入完整的 Power BI 嵌入链接",
      clear: "清除",
      cancel: "取消",
      save: "保存并嵌入",
    },
    pageSpeed: {
      added: "API 密钥已添加",
      addedEnableCwv: "API 密钥已添加，请切换开关以启用核心网页指标分析",
      title: "粘贴你的 Google PageSpeed Insights API 密钥",
      connect: "连接",
    },
    gscAnalytics: {
      fetchFailed: "获取 GSC 数据失败",
      noData: "没有可下载的数据",
      csvSaved: "CSV 文件已保存成功！",
      csvSavedDesc: "文件已保存到你选择的位置。",
      downloadCancelled: "已取消下载",
      downloadCancelledDesc: "你取消了文件保存对话框。",
      downloadFailed: "下载 CSV 文件失败",
      downloadFailedDesc: "请重试。",
      refreshing: "正在从 Google Search Console 获取最新数据…",
      refreshed: "Search Console 数据已更新",
      refreshFailedPrefix: "刷新 Search Console 数据失败：",
      columns: {
        keyword: "关键词",
        impressions: "展现",
        clicks: "点击",
        ctr: "点击率",
        position: "排名",
        url: "URL",
        date: "日期",
      },
      connectedTitle: "Search Console",
      connectedTo: "已连接到 {url}",
      reconnect: "重新连接",
      emptyTitle: "连接 Search Console",
      emptyDescription:
        "集成 Google Search Console 后，你可以直接在 RustySEO 中查看站点表现、索引状态和关键词排名。",
      getStarted: "开始配置",
      searchPlaceholder: "搜索关键词或 URL…",
      downloadTitle: "下载 CSV",
      refreshTitle: "刷新数据",
    },
  },
  page: {
    noUrlProvided: "未提供 URL",
    deviceOptions: {
      desktop: "桌面端",
      mobile: "移动端",
    },
    placeholder: "https://你的网址.com",
    crawl: "抓取",
    tabs: {
      diagnostics: "诊断",
      improvements: "优化建议",
      taskManager: "任务管理",
      crawlHistory: "抓取历史",
      searchConsole: "Search Console",
      tracking: "排名跟踪",
      content: "内容",
    },
    widgets: "指标卡片",
    serpPreview: "搜索结果预览",
    headings: {
      title: "标题标签",
      menuTitle: "标题标签",
      improve: "优化标题",
      generating: "生成中…",
      found: "已发现标题数",
      anchor: "标签",
      text: "文本",
      aiEmpty: "点击“优化标题”以生成 AI 建议。",
      copied: "已复制到剪贴板",
      type: "类型",
      originalText: "原始文本",
      recommendedText: "建议文本",
      aiGenerating: "AI 正在生成建议…",
      noAiGenerated:
        "未生成 AI 标题建议，请检查 API 密钥后重试。",
      errorGeneratingPrefix: "生成 AI 标题时出错：",
      commandNotFound: "未找到命令，请检查后端是否正在运行。",
      apiError: "API 错误，请检查你的 API 密钥。",
      genericRetry: "请重试，或查看控制台详情。",
      unknown: "未知",
    },
    analyticsModal: {
      saved: "GA4 ID 已添加成功",
      prompt: "输入你的 Google Analytics 4 属性 ID",
      connect: "连接",
    },
    clarityModal: {
      saved: "Microsoft Clarity 凭据已保存成功",
      getToken: "在这里获取 Token",
      endpoint: "接口地址",
      token: "令牌",
      tokenPlaceholder: "在此输入你的令牌",
      connect: "连接",
    },
    topicsMenu: {
      copied: "关键词已复制到剪贴板",
      title: "检查关键词",
      copyKeyword: "复制关键词",
      googleTrends: "Google 趋势",
      searchConsole: "Search Console",
    },
    todo: {
      drawerTitle: "待办事项",
      taskAdded: "任务已添加",
      requiredFields: "请填写所有必填字段",
      labels: {
        title: "任务标题",
        description: "任务说明",
        type: "类型",
        priority: "优先级",
        pageUrl: "页面 URL",
      },
      placeholders: {
        title: "输入任务标题",
        description: "输入任务说明",
        type: "选择任务类型",
        priority: "选择优先级",
      },
      addTask: "添加任务",
      statuses: {
        todo: "待办",
      },
      priorities: {
        low: "低",
        medium: "中",
        high: "高",
      },
      taskTypes: {
        head: "头部信息",
        content: "内容",
        links: "链接",
        images: "图片",
        headings: "标题",
        keywords: "关键词",
        schema: "结构化数据",
      },
    },
  },
  global: {
    searchPlaceholder: "搜索…",
    shared: {
      loading: "加载中…",
      export: "导出",
      searchColumns: "搜索列…",
      noColumnFound: "未找到列。",
      total: "总数",
      percent: "%",
      copyUrl: "复制 URL",
      openUrl: "打开 URL",
      searchOn: "搜索于…",
    },
    subtables: {
      noDataToExport: "没有可导出的数据",
      exportError: "导出错误",
      exportComplete: "导出完成",
      csvSaved: "CSV 文件已保存成功！",
      exportFailedPrefix: "导出 CSV 失败：",
      selectUrlToViewDetails: "请先在 HTML 表格中选择一个 URL 以查看详情",
      export: "导出",
      anchorText: "锚文本",
      relativeLink: "相对链接",
      absoluteLink: "绝对链接",
      link: "链接",
      status: "状态",
      statusCode: "状态码",
      searchPlaceholder: "搜索…",
      metaDescription: "Meta 描述",
      metaDescriptionLength: "Meta 描述长度",
    },
    tabs: {
      deepCrawl: "深度抓取",
      taskManager: "任务管理",
      searchConsole: "Search Console",
      tracking: "排名跟踪",
      content: "内容",
    },
    input: {
      placeholder: "分析域名…",
      crawl: "抓取",
      recent: "最近抓取",
    },
    tables: {
      html: "HTML",
      css: "CSS",
      javascript: "JavaScript",
      internal: "内链",
      external: "外链",
      images: "图片",
      keywords: "关键词",
      cwv: "核心网页指标",
      customSearch: "自定义搜索",
      redirects: "重定向",
      files: "文件",
      details: "详情",
      inlinks: "入链",
      outlinks: "出链",
      schema: "结构化数据",
      headers: "响应头",
      opengraph: "Open Graph",
      pageInternal: "页面内链",
      pageExternal: "页面外链",
      defaultContent: "默认内容",
      response404: "404 响应内容",
    },
    sidebar: {
      urlTree: {
        root: "网站根目录",
        empty: "暂无抓取数据可生成树状结构。",
        title: "站点树",
        totalPages: "总页面数",
        totalFolders: "总目录数",
        maxDepth: "最大深度",
        pageActions: "页面操作",
        folderActions: "目录操作",
        urlCopied: "URL 已复制到剪贴板",
        noUrlForFolder: "该目录没有可用 URL",
        pathCopied: "路径已复制到剪贴板",
        openFailed: "在浏览器中打开 URL 失败",
        focusTable: "已在 HTML 表格中定位该页面",
        quickAudit: "已切换到详情页分析",
        noDetailData: "未找到该 URL 的详细数据",
        externalToolFailed: "打开外部工具失败：{error}",
        openInBrowser: "在浏览器中打开",
        viewInTable: "在表格中查看",
        quickAuditLabel: "快速诊断",
        richResultsTest: "富媒体结果测试",
        securityHeaders: "安全响应头",
        socialDebuggers: "社交调试工具",
        validation: "校验工具",
        schemaValidator: "Schema 校验器",
        copyUrl: "复制 URL",
        copyPathSegment: "复制路径片段",
        filterByFolderSoon: "按目录筛选功能即将上线…",
        filterByFolder: "按目录筛选",
      },
      dropdowns: {
        processing: "处理中…",
        summary: "汇总",
        pagesCrawled: "已抓取页面",
        totalLinksFound: "发现链接总数",
        totalInternalLinks: "内链总数",
        totalExternalLinks: "外链总数",
        totalIndexablePages: "可索引页面数",
        totalNotIndexablePages: "不可索引页面数",
        chromeUxReport: "Chrome UX 报告",
        performanceScore: "性能得分",
        accessibilityScore: "无障碍得分",
        bestPractices: "最佳实践",
        seoScore: "SEO 得分",
        goodRange: "良好（90-100）",
        needsImprovement: "需改进",
        poorRange: "较差（0-49）",
        metaDescription: "Meta 描述",
        totalDescription: "描述总数",
        emptyDescription: "空描述",
        duplicateDescription: "重复描述",
        over155Characters: "超过 155 个字符",
        below70Characters: "低于 70 个字符",
        url: "URL",
        total: "总数",
        nonAsciiCharacters: "非 ASCII 字符",
        underscores: "下划线",
        uppercase: "大写字母",
        multipleSlashes: "多重斜杠",
        repetitivePath: "重复路径",
        containsSpace: "包含空格",
        internalSearch: "站内搜索",
        parameters: "参数",
        over115Characters: "超过 115 个字符",
      },
      queryMenu: {
        copied: "查询词已复制到剪贴板",
        credentialsMissing: "未找到 Search Console 凭据",
        queryRequired: "无法添加关键词：必须提供查询词",
        invalidData: "检测到无效数据，请检查控制台详情",
        addedToTracking: "关键词已添加到跟踪面板",
        alreadyTracked: "该关键词已存在于跟踪中",
        missingRequired: "关键词跟踪缺少必要数据",
        databaseTimeout: "数据库保存超时，请检查后端",
        syncTimeout: "表格同步超时，请检查后端",
        operationTimeout: "整体操作超时，请检查后端连接",
        addFailedPrefix: "添加关键词到跟踪失败：",
        copyQuery: "复制查询词",
        addToTracking: "添加到跟踪",
        openInSearchConsole: "在 Search Console 中打开",
        serpResults: "搜索结果页",
        backlinks: "反向链接",
      },
      console: {
        crawlerEngine: "抓取引擎",
        aiNeural: "AI 模型",
        psiInsights: "PSI 洞察",
        googleAnalytics: "Google Analytics",
        msClarity: "MS Clarity",
        searchConsole: "Search Console",
        operationStatus: "运行状态",
        workloadQueue: "任务队列",
        spider: "爬虫",
        connected: "已连接",
        offline: "离线",
        running: "运行中",
        notConfigured: "未配置",
        authorized: "已授权",
        required: "需要配置",
        busy: "忙碌",
        done: "完成",
        idle: "空闲",
        empty: "空",
        tasks: "{count} 个任务",
        systemDiagnostic: "系统诊断",
        uptime: "运行时长",
        secure: "安全",
        active: "活跃",
      },
      cssTable: {
        searchPlaceholder: "搜索…",
      },
      charts: {
        visitors: "数量",
        html: "页面",
        safari: "合规",
        firefox: "问题",
        edge: "临界",
        other: "其他",
        totalPages: "总页面数",
        pages: "页面",
        fromTotalPagesAnalyzed: "基于已分析的 {count} 个页面",
        issuesFound: "发现问题",
        missing: "缺失",
        contains: "包含",
        h1Missing: "H1 缺失",
        h1MissingFound: "发现 {count} 个页面缺少 H1。",
        sessionRecordedCrawls: "本次会话已记录 {count} 次抓取。",
        totalPagesAnalyzed: "共分析了 {count} 个页面",
        crawled: "已抓取",
        errors4xx: "4XX 错误",
        errors5xx: "5XX 错误",
        queued: "排队中",
        latestCrawl: "最近一次抓取",
      },
    },
    diffChecker: {
      unknownError: "发生未知错误",
      notAvailable: "暂无",
      websiteMismatch: "抓取网站不一致",
      mismatchDescription: "上一次抓取与当前抓取的网站不同，无法进行对比。",
      previousCrawl: "上一次抓取：",
      currentCrawl: "当前抓取：",
      noPreviousWebsite: "之前没有抓取过网站",
      noChanges: "两次抓取之间没有新增或移除 URL",
      changesDetected: "RustySEO 检测到两次抓取之间存在变化",
      previous: "上一次：",
      current: "当前：",
      addedPages: "新增页面",
      removedPages: "移除页面",
      pages: "页",
      newCount: "+{count} 个新增",
      removedCount: "-{count} 个移除",
      newUrls: "新增 URL（{count}）",
      removedUrls: "移除 URL（{count}）",
      noNewUrls: "自上次抓取后没有新增 URL",
      noRemovedUrls: "两次抓取之间没有检测到移除的 URL",
    },
  },
  ppc: {
    tabs: {
      content: "内容",
      assets: "素材",
      targeting: "定向",
      settings: "设置",
    },
    adTypes: {
      search: "搜索广告",
      pmax: "效果最大化",
      display: "展示广告",
    },
    form: {
      exportSuccess: "广告已导出为 Google Ads CSV",
      importSuccess: "广告导入成功",
      importFailed: "导入 CSV 失败，请检查格式。",
      clearConfirm: "确定要清空所有字段吗？",
      cleared: "表单已清空",
      saved: "广告已保存",
      selectAdType: "选择广告类型",
      creativeTitle: "广告创意",
      creativeDescription: "定义你的广告信息与落地页",
      adName: "广告名称",
      adNamePlaceholder: "输入广告版本名称",
      businessName: "商家名称",
      businessNamePlaceholder: "你的品牌名称",
      finalUrl: "最终链接",
      headlines: "标题",
      headlinePlaceholder: "标题 {index}",
      descriptions: "描述",
      descriptionPlaceholder: "描述 {index}",
      visualCreatives: "视觉素材",
      marketingImages: "营销图片",
      marketingImagesDescription: "上传高质量品牌视觉素材",
      logos: "Logo",
      logosDescription: "添加方形和横向 Logo",
      targetingTitle: "定向与关键词",
      targetingDescription: "定义哪些用户会看到你的广告",
      targetKeywords: "目标关键词（每行一个）",
      targetKeywordsPlaceholder: "例如：数字营销\nSEO 工具\n广告模拟器",
      settingsTitle: "广告系列策略",
      settingsDescription: "配置预算与竞价策略",
      preview: "预览",
      import: "导入",
      export: "导出",
      clear: "清空",
      saveCampaign: "保存广告系列",
    },
    dashboard: {
      newAd: "新广告",
      adCreated: "广告已创建",
      adCreatedDescription: "“{name}”已成功创建",
      adCloned: "广告已复制",
      adClonedDescription: "“{name}”已成功复制",
      adDeleted: "广告已删除",
      adDeletedDescription: "“{name}”已删除",
      adDeletedFallback: "广告已删除",
      error: "错误",
      deleteFailed: "删除广告失败，请重试。",
      adSaved: "广告已保存",
      adSavedDescription: "“{name}”已成功保存",
      preview: "预览",
      editorTitle: "广告编辑器",
      editorDescription: "优化你的标题、描述和素材",
      headerEditAd: "编辑广告",
      headerAllAds: "全部广告",
      headerPreviews: "广告预览",
      headerSettings: "设置",
      headerDashboard: "控制台",
      descEditAd: "编辑广告详情",
      descManageAds: "管理你的 Google 搜索广告",
      descPreviews: "预览广告展示效果",
      descSettings: "配置账户设置",
      descDashboard: "Google 搜索广告概览",
      myAds: "我的广告",
    },
    preview: {
      emptyTitle: "暂无广告",
      emptyDescription: "创建一个广告后即可在这里预览",
      title: "RustySEO 预览",
      live: "实时",
      adCount: "广告 {current} / {total}",
      modes: {
        search: "搜索",
        display: "展示",
        mobile: "移动端",
        youtube: "YouTube",
      },
      headlines: "标题",
      description: "描述",
      empty: "空",
      noDescription: "暂无描述",
      sponsored: "广告",
      call: "电话",
      addHeadlinesHint: "[请在表单中添加标题]",
      addDescriptionHint: "[描述将显示在这里]",
      skipIn: "可跳过于",
      adLabel: "广告",
      youtubeHeadline: "[视频广告标题待填写]",
      youtubeDescription: "[互动型描述待填写]",
      experienceNow: "立即体验",
      mobileHeadline: "[爆款标题]",
      mobileDescription: "[吸引用户第一眼点击的广告文案]",
      thumbnailNoHeadline: "[暂无标题]",
      thumbnailNoDescription: "[暂无描述]",
      headlineCount: "{count} 个标题",
      displayHeadline: "[高转化商业标题]",
      displayDescription: "[你的展示广告描述会在这里吸引用户注意]",
      exploreNow: "立即探索",
    },
    importExport: {
      export: "导出",
      exportJson: "导出为 JSON",
      exportCsv: "导出为 CSV",
      import: "导入",
      importTitle: "导入广告",
      importDescription: "上传包含广告数据的 JSON 或 CSV 文件。",
      dragAndDrop: "将文件拖放到此处，或点击浏览",
      browseFiles: "浏览文件",
      cancel: "取消",
      exportSuccess: "导出成功",
      exportSuccessDescription: "已将 {count} 条广告导出为 {format}",
      exportFailed: "导出失败",
      importSuccess: "导入成功",
      importSuccessDescription: "已导入 {count} 条广告",
      importFailed: "导入失败",
      unknownError: "未知错误",
      readFailed: "读取文件失败",
      unsupportedFormat: "不支持的文件格式，请使用 JSON 或 CSV。",
      noFileSelected: "未选择文件",
      dataFiles: "数据文件",
    },
    sitelinks: {
      title: "附加链接",
      description: "最多添加 6 个主广告下方的次级链接",
      add: "添加附加链接",
      empty: "尚未添加附加链接",
      untitled: "未命名附加链接",
      linkText: "链接文本",
      linkTextPlaceholder: "例如：立即购买",
      linkUrl: "链接地址",
      description1: "描述行 1",
      description2: "描述行 2",
      description1Placeholder: "第一行描述",
      description2Placeholder: "第二行描述",
      maxChars: "最多 25 个字符",
    },
    extensions: {
      title: "广告附加信息",
      description: "添加素材以提升广告表现",
      add: "添加",
      empty: "尚未添加附加信息",
      types: {
        callout: "附加说明",
        structured_snippet: "结构化摘要",
        call: "电话",
        promotion: "促销",
      },
      placeholders: {
        call: "电话号码",
        default: "附加信息文本",
        promotion: "促销代码（可选）",
      },
    },
    adList: {
      emptyTitle: "尚未创建广告",
      emptyDescription: "创建你的第一个广告以开始使用",
      allAds: "全部广告",
      noAdsFound: "未找到 {type} 广告",
      noAdsFoundDescription: "创建新广告或切换到其他分类",
      updated: "更新于",
      primaryHeadline: "主标题",
      noHeadlines: "暂无标题",
      assets: "素材",
      headlines: "标题",
      descriptionsShort: "描述",
      keywords: "关键词",
      editAd: "编辑广告",
      cloneAd: "复制广告",
      confirmDelete: "点击确认删除",
      deleteAd: "删除广告",
    },
    layout: {
      title: "Google Ads 模拟器",
    },
    campaignSettings: {
      dailyBudget: "每日预算",
      dailyBudgetDescription: "你希望每天平均花费的金额。",
      biddingStrategy: "竞价策略",
      biddingStrategies: {
        maximize_clicks: "最大化点击",
        maximize_conversions: "最大化转化",
        manual_cpc: "手动 CPC",
        target_roas: "目标 ROAS",
        target_cpa: "目标 CPA",
      },
      locationTargeting: "地域定向",
      locationPlaceholder: "例如：美国、伦敦、东京",
      languages: "语言",
      languagesPlaceholder: "例如：中文、英语、西班牙语",
      startDate: "开始日期",
      endDate: "结束日期",
    },
    keywordValidator: {
      optimizedTitle: "广告文案已优化",
      optimizedDescription:
        "很好，你的目标关键词都已正确包含在广告标题和描述中。",
      requiredTitle: "需要优化",
      requiredDescription: "以下关键词目前尚未出现在你的广告创意中：",
    },
    imageManager: {
      maxFilesError: "最多只能上传 {count} 张图片",
      notImageError: "{name} 不是图片文件",
      tooLargeError: "{name} 过大（最大 5MB）",
      uploadPrompt: "点击上传或拖拽到此处",
      uploadLimit: "最多 {count} 张图片（每张最大 5MB）",
    },
  },
  serverlogs: {
    loadGoogleIpsFailed: "RustySEO 加载 Google IP 段失败",
    allLogsRemoved: "数据库中的所有日志已移除",
    chartViews: {
      overall: "整体流量",
      crawlers: "AI 爬虫",
      status: "HTTP 状态",
    },
    upload: {
      uploadLogs: "上传日志",
      uploadTooltip: "上传或追加日志",
      gscTooltip: "查看 Google Search Console 数据",
      settingsTooltip: "设置",
      clearLogs: "移除日志",
      clearLogsTooltip: "清空所有日志",
      cacheCleared: "已清除之前缓存的日志",
      tabs: {
        domain: "域名",
        taxonomy: "内容分段",
        logs: "已存日志",
        gsc: "GSC 同步",
        projects: "项目",
      },
    },
    domain: {
      empty: "域名不能为空",
      invalid: "请输入有效域名",
      added: "已添加域名",
      noDomain: "没有可提交的域名",
      saved: "设置已保存",
      saveFailed: "设置保存失败",
      retryLater: "请稍后重试",
      title: "设置域名",
      placeholder: "输入你的域名（例如 example.com）",
      add: "添加",
      currentDomain: "当前域名",
      removeDomain: "移除域名",
      noDomainYet: "尚未设置域名",
      showOnTables: "在表格中显示域名",
      help:
        "输入你的主域名以启用站点级功能。这里应填写不带协议的根域名，例如 “example.com”，而不是 “https://example.com”。",
      saving: "正在保存设置…",
      saveReload: "保存设置并重新加载",
      showOnTablesYes: "是",
      showOnTablesNo: "否",
    },
    gsc: {
      uploadInvalid: "请上传 .xlsx 或 .csv 文件",
      detected: "已检测到 Google Sheets 文件，请选择要处理的工作表",
      noPages: "此文件中未找到 Pages 数据",
      selectPages: "请选择包含正确数据的工作表，必须为 “Pages”",
      processed: "文件已处理并成功加载",
      memoryLoaded: "GSC 数据已加载到内存",
      fileUpload: "文件上传",
      clickUpload: "点击上传",
      dragDrop: "或拖拽到此处",
      selectSheet: "选择工作表",
    processing: "处理中…",
    processData: "处理数据",
    processFailed: "处理失败",
    preview: "数据预览",
      loadedRows: "已加载",
      rows: "行",
      emptyPreview: "选择文件和工作表后可预览数据",
      fileFallback: "文件",
      loadMemoryFailed: "加载到内存失败",
      loadedCount: "已加载 GSC 条记录到内存",
    },
    analyzer: {
      searchPlaceholder: "按 IP、路径、User Agent 搜索…",
      search: "搜索",
      status: "状态",
      method: "方法",
      fileType: "文件类型",
      filterByStatus: "按状态筛选",
      filterByMethod: "按方法筛选",
      filterByFileType: "按文件类型筛选",
      success: "成功",
      redirection: "重定向",
      clientError: "客户端错误",
      serverError: "服务端错误",
      botHuman: "爬虫/人工",
      allRequests: "全部请求",
      robots: "机器人",
      human: "人工",
      pathMode: "路径",
      pathUrl: "路径 / URL",
      userAgent: "User Agent",
      allDevices: "全部设备",
      desktop: "桌面端",
      mobile: "移动端",
      verification: "校验状态",
      allIps: "全部 IP",
      verified: "已验证",
      unverified: "未验证",
      reset: "重置",
      exporting: "导出中…",
      exportCsv: "导出 CSV",
      exportCancelled: "已取消导出。",
      exportSuccess: "CSV 导出成功！",
      exportFailed: "导出失败",
      noEntries: "未找到日志记录。",
      ipAddress: "IP 地址",
      browser: "浏览器",
      timestamp: "时间戳",
      path: "路径",
      position: "排名",
      clicks: "点击",
      impressionsShort: "展现",
      segment: "分段",
      size: "大小",
      crawlerType: "爬虫类型",
      inspectIp: "点击查看 IP",
      referer: "来源页",
      noReferer: "无来源页",
      of: "共",
    },
  },
  onboarding: {
    title: "快速引导",
    start: "开始",
    finish: "完成",
    allDone: "已完成",
    completed: "你已完成引导流程。",
    startOver: "重新开始",
    close: "关闭",
    back: "上一步",
    next: "下一步",
    done: "完成",
    imageAltPrefix: "插图：",
    steps: [
      {
        id: 1,
        title: "欢迎使用 RustySEO",
        description:
          "一站式营销工具，面向希望把 SEO 与 GEO 工作集中到同一套工具中的专业用户。",
        helper: "先用几个简单步骤快速了解核心能力。",
      },
      {
        id: 2,
        title: "浅层抓取（单页）",
        description:
          "针对单个页面进行精细分析，结合 AI 洞察与性能建议，帮助你快速定位并解决问题。",
        helper: "适合页面级、站外与技术 SEO 检查。",
      },
      {
        id: 3,
        title: "深度抓取（批量）",
        description:
          "抓取整个网站并输出可执行洞察。RustySEO 能识别错误、给出方向，帮助你发现更深层的问题。",
        helper: "适合批量分析与整站优化。",
      },
      {
        id: 4,
        title: "日志分析",
        description:
          "分析 Apache/Nginx 服务器日志，了解爬虫访问时序、抓取频次与内容分类等关键数据。",
        helper: "非常适合抓取预算分析。",
      },
      {
        id: 5,
        title: "连接器与集成",
        description:
          "接入你常用的平台与工具，包括 PageSpeed Insights、Google Search Console、Google Analytics、Microsoft Clarity、Power BI 等。",
        helper: "把 SEO 相关数据集中到一个工作台中。",
      },
      {
        id: 6,
        title: "关键词跟踪与内容探索",
        description:
          "跟踪关键词表现，识别模式，并在优化页面时获取新的内容创意与建议。",
        helper: "适合内容优化与选题扩展。",
      },
      {
        id: 7,
        title: "还有更多功能",
        description:
          "RustySEO 还提供更多高级能力与集成。欢迎通过反馈和贡献帮助项目继续完善。",
        helper: "欢迎体验，也欢迎通过 GitHub 告诉我们你的想法。",
      },
    ],
  },
  sidebar: {
    topTabs: {
      general: "总览",
      content: "内容",
      suggestions: "建议",
      queries: "查询",
    },
    bottomTabs: {
      checklist: "检查清单",
      redirects: "重定向",
      robots: "Robots",
      domain: "域名",
    },
    groups: {
      coreWebVitals: "核心网页指标",
      seo: "SEO",
      content: "内容",
    },
    passed: "通过",
    failed: "未通过",
    notAvailable: "暂无",
    rustyFeedback: "Rusty 反馈",
    overallScore: "综合得分",
    topRecommendation: "优先建议：先提升页面加载速度，并补充内容深度。",
  },
};

export const zhCheckNameMap: Record<string, string> = {
  Performance: "性能",
  "First Contentful Paint": "首次内容绘制",
  "Largest Contentful Paint": "最大内容绘制",
  "Time to Interactive": "可交互时间",
  "Total Blocking Time": "总阻塞时间",
  "Cumulative Layout Shift": "累计布局偏移",
  "Speed Index": "速度指数",
  "Server Response Time": "服务器响应时间",
  "Total Byte Weight": "总字节体积",
  "DOM Size": "DOM 大小",
  "URL Redirects": "URL 重定向",
  "Long Tasks": "长任务",
  "Render Blocking Resources": "阻塞渲染资源",
  "Network Requests": "网络请求数",
  "URL length": "URL 长度",
  Favicon: "网站图标",
  "Page Title": "页面标题",
  "Page Description": "页面描述",
  Canonical: "规范链接",
  Hreflangs: "Hreflang 标记",
  OpenGraph: "Open Graph",
  "Structured Data": "结构化数据",
  "Page Charset": "页面字符集",
  Indexability: "可索引性",
  "Images Alt Text": "图片 Alt 文本",
  "404 Links": "404 链接",
  "Repeated Headings": "重复标题",
  "Word Count": "字数",
  "Reading Time": "阅读时长",
  "Keyword Density": "关键词密度",
  "Reading Level": "可读性等级",
  "Content Structure": "内容结构",
  "Media / Video": "媒体 / 视频",
};

export const zhStatusMap: Record<string, string> = {
  Passed: "通过",
  Failed: "未通过",
  Excellent: "优秀",
  Good: "良好",
  "Needs Improvement": "需改进",
  Poor: "较差",
  Unknown: "未知",
  Acceptable: "可接受",
  Optimal: "最佳",
  Unacceptable: "不可接受",
  "Very Easy": "非常易读",
  Easy: "易读",
  "Fairly Easy": "较易读",
  Standard: "标准",
  "Fairly Difficult": "较难读",
  Difficult: "困难",
  "Very Confusing": "非常难懂",
};
